name: 'Hello World'
description: 'Hello'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
outputs:
  message:
    value: ${{ steps.define-message.outputs.message }}
runs:
  using: "composite"
  steps:
    #- run: echo Hello World
    - run: echo Hello ${{ inputs.who-to-greet }}
      shell: bash
    
    - name: confirm work directory
      run: |
        echo ${{ github.action_path }}
        ls -lR ${{ github.action_path }}
        ${{ github.action_path }}/script/hello.sh
      shell: bash

    - name: define message
      id: define-message
      run: echo "message=Hello from custom action." >> "$GITHUB_OUTPUT"
      shell: bash